apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service
spec:
  selector:
    app: shopping-cart
  ports:
    - protocol: TCP
      port: 80        # External port (exposed to users)
      targetPort: 8083 # The actual port inside the container
      nodePort: 30080
  type: NodePort
